# Puerto del servidor (Railway inyecta la variable PORT automáticamente)
server.port=${PORT:8080}

# Desactivar Spring Cloud Config Server
spring.cloud.config.enabled=false

# Nombre de la aplicación
spring.application.name=prueba

# Base de datos PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-wild-voice-ae85w8fa-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Pah7UFy1EjJk
spring.datasource.driver-class-name=org.postgresql.Driver

# URL y credenciales de GestoPago (evita el error de malformed URL)
gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678
gestopago.auth.refresh-rate-ms=3600000

# Configuración de Servicios de Productos GestoPago
gestopago.service.url=https://gestopago.portalventas.net
gestopago.service.connect-timeout-ms=5000
gestopago.service.read-timeout-ms=10000

# -------------------------------------------------------------
# Configuración de Redis
# -------------------------------------------------------------
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=2000ms

# Clave donde se guardará el catálogo en Redis
gestopago.redis.catalogo-key=gestopago:catalogo:productos_por_tipo_front

# Tiempo de vida en Redis: 90000 segundos (25 horas para cubrir hasta el siguiente cron)
gestopago.redis.catalogo-ttl-seconds=90000

# -------------------------------------------------------------
# Configuración del Cron
# -------------------------------------------------------------
# Expresión cron para las 6:00 AM todos los días (segundo, minuto, hora, día, mes, día-semana)
gestopago.cron.catalogo=0 0 6 * * *
gestopago.cron.zone=America/Mexico_City

# Jackson: Mantener precision y escala exacta de decimales
spring.jackson.deserialization.use-big-decimal-for-floats=true
