# Desactivar Spring Cloud Config Server
spring.cloud.config.enabled=false

# Nombre de la aplicación
spring.application.name=prueba

# Base de datos PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-wild-voice-ae85w8fa-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Pah7UFy1EjJk
spring.datasource.driver-class-name=org.postgresql.Driver

# URL y credenciales de GestoPago (evita el error de malformed URL)
gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678
gestopago.auth.refresh-rate-ms=3600000

# Configuración de Servicios de Productos GestoPago
gestopago.service.url=https://gestopago.portalventas.net
gestopago.service.token=qmzAAEYFmqQbIT/Ktxme8Akih4Md6cXf9hTHKjfO626aEN8GrvSLaA9CJP3Q1UI5bL6/tDk+nsTwmGoUwm3VR+LPbGaB13DSSR2d+wUdceSEpPaXTHjGkAaxAFbkFjCYCsZ7OBoqVqUQXbstRwvUXQ==
gestopago.service.connect-timeout-ms=5000
gestopago.service.read-timeout-ms=10000